
---
title: "weatherOz for SILO"
author: "Rodrigo Pires, Anna Hepworth, Rebecca O'Leary and Adam H. Sparks"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{weatherOz for SILO}
  %\VignetteEngine{knitr::rmarkdown_notangle}
  %\VignetteEncoding{UTF-8}
bibliography: bibliography.bib
---



# About SILO Data

[Queensland Scientific Information for Landowners (SILO)](https://www.longpaddock.qld.gov.au/silo/about/) data sets are constructed from observational records provided by the Bureau of Meteorology (BOM).
SILO interpolates the raw data to fill missing data creating data sets that are spatially and temporally complete [@Jeffrey2001].

# Working With SILO Data

Four functions are provided to streamline fetching data from the SILO API endpoints.

 * `get_data_drill()`, which returns weather data from SILO's 0.05 x 0.05 degrees interpolated, gridded weather dataset;
 * `get_patched_point()`, which returns weather data from a given BOM weather station (a point) in the SILO database where missing values are interpolated (patched);
 * `get_data_drill_apsim()`, which returns data drill weather data in an {apsimx} `.met` class object with the weather data ready for use in APSIM; and
 * `get_patched_point_apsim()`, which returns patched point weather data in an {apsimx} `.met` class object with the weather data ready for use in APSIM.

## Available Values

`get_data_drill()` and `get_patched_point()` both accept the following values.
`get_data_drill_apsim()` and `get_patched_point_apsim()` return a canned set of values for use in APSIM, because of this, they do not accept a `values` argument.

<dl>
  <dt>all</dt><dd>Which will return all of the following values</dd>
  <dt>max_temp (degrees C)</dt><dd>Maximum temperature</dd>
  <dt>min_temp (degrees C)</dt><dd>Minimum temperature</dd>
  <dt>vp (hPa)</dt><dd>Vapour pressure</dd>
  <dt>vp_deficit (hPa)</dt><dd>Vapour pressure deficit</dd>
  <dt>evap_pan (mm)</dt><dd>Class A pan evaporation</dd>
  <dt>evap_syn (mm)</dt><dd>Synthetic estimate [@Rayner2005]</dd>
  <dt>evap_comb (mm)</dt><dd>Combination (synthetic estimate pre-1970, class A pan 1970 onwards)</dd>
  <dt>evap_morton_lake (mm)</dt><dd>Morton's shallow lake evaporation</dd>
  <dt>radiation (Mj/m [@Morton1983])</dt><dd>Solar exposure, consisting of both direct and diffuse components</dd>
  <dt>rh_tmax (%)</dt><dd>Relative humidity at the time of maximum temperature</dd>
  <dt>rh_tmin (%)</dt><dd>Relative humidity at the time of minimum temperature</dd>
  <dt>et_short_crop (mm)</dt><dd>FAO56 [@Allen1998] short crop</dd>
  <dt>et_tall_crop (mm)</dt><dd>ASCE [@Walter2000] tall crop [@Jeffrey2001]</dd>
  <dt>et_morton_actual (mm)</dt><dd>Morton's areal actual evapotranspiration</dd>
  <dt>et_morton_potential (mm)</dt><dd>Morton's point potential evapotranspiration</dd>
  <dt>et_morton_wet (mm)</dt><dd>Morton's wet-environment areal potential evapotranspiration over land</dd>
  <dt>mslp (hPa)</dt><dd>Mean sea level pressure</dd>
</dl>

## Value information

Solar radiation: total incoming downward shortwave radiation on a horizontal surface, derived from estimates of cloud oktas and sunshine duration [@Zajaczkowski2013].

Relative humidity: calculated using the vapour pressure measured at 9am, and the saturation vapour pressure computed using either the maximum or minimum temperature [@Jeffrey2001].

Evaporation and evapotranspiration: an overview of the variables provided by SILO is available as a [https://data.longpaddock.qld.gov.au/static/publications/Evapotranspiration_overview.pdf](PDF).

## Data Codes

Where possible (depending on the file format), the data are supplied with codes indicating how each datum was obtained.

<dl>
  <dt>0</dt><dd>Official observation as supplied by the Bureau of Meteorology</dd>
  <dt>15</dt><dd>Deaccumulated rainfall (original observation was recorded over a period exceeding the standard 24 hour observation period)</dd>
  <dt>25</dt><dd>Interpolated from daily observations for that date</dd>
  <dt>26</dt><dd>Synthetic Class A pan evaporation, calculated from temperatures, radiation and vapour pressure</dd>
  <dt>35</dt><dd>Interpolated from daily observations using an anomaly interpolation method</dd>
  <dt>75</dt><dd>Interpolated from the long term averages of daily observations for that day of year</dd>
</dl>

The data returned will include columns that denote the source of the data, whether it was an observation or interpolated.

## A Note on API Keys

All examples in this vignette assume that you have stored your API key in your .Renviron file.
See [Chapter 8](https://rstats.wtf/r-startup.html#renviron) in "What They Forgot to Teach You About R" by Bryan _et al._ for more on storing details in your .Renviron if you are unfamiliar.

## Getting Data Drill Interpolated Data

The `get_data_drill()` function fetches spatially interpolated data from SILO for any point in Australia.
Note that these data are not observations, but are interpolated surfaced derived by using either by splining or kriging the observational data.
The arguments required to use this function are minimal with few options.
The location as longitude and latitude, `longitude` and `latitude`, values must be provided along with the start date, `start_date` and the api key, `api_key` (your e-mail address).

### Example 1: Get Data Drill Data Using Defaults

Using coordinates for Southwood, Qld, get Data Drill data for all values available starting on 2022-01-01.


``` r
library(weatherOz)

(
  southwood <- get_data_drill(
    latitude = -27.85,
    longitude = 150.05,
    start_date = "20220101",
    api_key = Sys.getenv("SILO_API_KEY")
  )
)
#>      longitude latitude  year month   day       date air_tmax air_tmax_source
#>          <num>    <num> <num> <num> <int>     <Date>    <num>           <int>
#>   1:    150.05   -27.85  2022     1     1 2022-01-01     29.7              25
#>   2:    150.05   -27.85  2022     1     2 2022-01-02     33.6              25
#>   3:    150.05   -27.85  2022     1     3 2022-01-03     35.7              25
#>   4:    150.05   -27.85  2022     1     4 2022-01-04     36.3              25
#>   5:    150.05   -27.85  2022     1     5 2022-01-05     36.4              25
#>  ---                                                                         
#> 866:    150.05   -27.85  2024     5    15 2024-05-15     25.2              25
#> 867:    150.05   -27.85  2024     5    16 2024-05-16     24.5              25
#> 868:    150.05   -27.85  2024     5    17 2024-05-17     23.7              25
#> 869:    150.05   -27.85  2024     5    18 2024-05-18     21.9              25
#> 870:    150.05   -27.85  2024     5    19 2024-05-19     22.5              75
#>      air_tmin air_tmin_source  elev_m et_morton_actual et_morton_actual_source
#>         <num>           <int>  <char>            <num>                   <int>
#>   1:     18.8              25 254.5 m              4.3                      26
#>   2:     16.6              25 254.5 m              6.2                      26
#>   3:     18.1              25 254.5 m              4.3                      26
#>   4:     18.1              25 254.5 m              5.1                      26
#>   5:     20.3              25 254.5 m              5.0                      26
#>  ---                                                                          
#> 866:      9.1              25 254.5 m              1.8                      26
#> 867:     11.8              25 254.5 m              1.2                      26
#> 868:     12.9              25 254.5 m              2.1                      26
#> 869:      8.7              25 254.5 m              1.7                      26
#> 870:      5.6              25 254.5 m              0.8                      26
#>      et_morton_potential et_morton_potential_source et_morton_wet
#>                    <num>                      <int>         <num>
#>   1:                 7.2                         26           5.7
#>   2:                 9.6                         26           7.9
#>   3:                11.5                         26           7.9
#>   4:                11.1                         26           8.1
#>   5:                10.9                         26           8.0
#>  ---                                                             
#> 866:                 3.6                         26           2.7
#> 867:                 3.3                         26           2.2
#> 868:                 3.2                         26           2.6
#> 869:                 3.6                         26           2.6
#> 870:                 4.6                         26           2.7
#>      et_morton_wet_source et_short_crop et_short_crop_source et_tall_crop
#>                     <int>         <num>                <int>        <num>
#>   1:                   26           5.2                   26          6.3
#>   2:                   26           7.0                   26          8.6
#>   3:                   26           7.7                   26          9.9
#>   4:                   26           7.7                   26          9.7
#>   5:                   26           7.5                   26          9.4
#>  ---                                                                     
#> 866:                   26           2.6                   26          3.5
#> 867:                   26           2.4                   26          3.2
#> 868:                   26           2.3                   26          2.9
#> 869:                   26           2.4                   26          3.2
#> 870:                   26           2.8                   26          4.1
#>      et_tall_crop_source evap_comb evap_comb_source evap_morton_lake
#>                    <int>     <num>            <int>            <num>
#>   1:                  26       5.0               25              6.0
#>   2:                  26       9.2               25              8.3
#>   3:                  26       8.1               25              8.3
#>   4:                  26       8.6               25              8.5
#>   5:                  26       6.3               25              8.3
#>  ---                                                                
#> 866:                  26       2.7               25              2.7
#> 867:                  26       1.9               25              2.2
#> 868:                  26       2.6               25              2.6
#> 869:                  26       3.5               25              2.7
#> 870:                  26       3.0               75              2.8
#>      evap_morton_lake_source evap_pan evap_pan_source evap_syn evap_syn_source
#>                        <int>    <num>           <int>    <num>           <int>
#>   1:                      26      5.0              25      6.8              26
#>   2:                      26      9.2              25      9.2              26
#>   3:                      26      8.1              25     10.5              26
#>   4:                      26      8.6              25     10.4              26
#>   5:                      26      6.3              25     10.1              26
#>  ---                                                                          
#> 866:                      26      2.7              25      3.2              26
#> 867:                      26      1.9              25      2.9              26
#> 868:                      26      2.6              25      2.8              26
#> 869:                      26      3.5              25      3.0              26
#> 870:                      26      3.0              75      3.5              26
#>       extracted   mslp mslp_source radiation radiation_source rainfall
#>          <Date>  <num>       <int>     <num>            <int>    <num>
#>   1: 2024-05-20 1011.8          25      22.6               42     54.9
#>   2: 2024-05-20 1008.5          25      31.3               42      0.1
#>   3: 2024-05-20 1005.1          25      31.3               42      0.0
#>   4: 2024-05-20 1005.1          25      31.3               42      0.0
#>   5: 2024-05-20 1005.5          25      29.8               42      0.0
#>  ---                                                                  
#> 866: 2024-05-20 1027.5          25      14.3               42      0.0
#> 867: 2024-05-20 1027.2          25      11.6               42      0.0
#> 868: 2024-05-20 1024.5          25      13.7               42      2.3
#> 869: 2024-05-20 1020.4          25      15.0               42      0.1
#> 870: 2024-05-20 1022.0          25      16.0               25      0.0
#>      rainfall_source rh_tmax rh_tmax_source rh_tmin rh_tmin_source    vp
#>                <int>   <num>          <int>   <num>          <int> <num>
#>   1:              25    48.0             26    92.2             26  20.0
#>   2:              25    36.3             26   100.0             26  18.9
#>   3:              25    26.5             26    74.7             26  15.5
#>   4:              25    29.1             26    84.8             26  17.6
#>   5:              25    32.3             26    82.3             26  19.6
#>  ---                                                                    
#> 866:              25    45.6             26   100.0             26  14.6
#> 867:              25    50.1             26   100.0             26  15.4
#> 868:              25    57.7             26   100.0             26  16.9
#> 869:              25    48.0             26   100.0             26  12.6
#> 870:              25    33.8             26   100.0             26   9.2
#>      vp_deficit vp_deficit_source vp_source
#>           <num>             <int>     <int>
#>   1:       15.6                26        25
#>   2:       22.0                26        25
#>   3:       30.2                26        25
#>   4:       29.3                26        25
#>   5:       29.0                26        25
#>  ---                                       
#> 866:       10.5                26        25
#> 867:       10.0                26        25
#> 868:        8.0                26        25
#> 869:        8.8                26        25
#> 870:       11.8                26        25
```

### Example 2: Get Data Drill Temperature for a Specific Date Range

Using coordinates for Southwood, Qld, get Data Drill temperature data for January of 2023.


``` r
library(weatherOz)

(
  southwood_temp <- get_data_drill(
    latitude = -27.85,
    longitude = 150.05,
    start_date = "20230101",
    end_date = "20230131",
    values = c("max_temp", "min_temp"),
    api_key = Sys.getenv("SILO_API_KEY")
  )
)
#>     longitude latitude  year month   day       date air_tmax air_tmax_source
#>         <num>    <num> <num> <num> <int>     <Date>    <num>           <int>
#>  1:    150.05   -27.85  2023     1     1 2023-01-01     35.2              25
#>  2:    150.05   -27.85  2023     1     2 2023-01-02     35.3              25
#>  3:    150.05   -27.85  2023     1     3 2023-01-03     36.6              25
#>  4:    150.05   -27.85  2023     1     4 2023-01-04     39.1              25
#>  5:    150.05   -27.85  2023     1     5 2023-01-05     31.4              25
#>  6:    150.05   -27.85  2023     1     6 2023-01-06     34.4              25
#>  7:    150.05   -27.85  2023     1     7 2023-01-07     33.4              25
#>  8:    150.05   -27.85  2023     1     8 2023-01-08     35.8              25
#>  9:    150.05   -27.85  2023     1     9 2023-01-09     36.4              25
#> 10:    150.05   -27.85  2023     1    10 2023-01-10     38.0              25
#> 11:    150.05   -27.85  2023     1    11 2023-01-11     33.3              25
#> 12:    150.05   -27.85  2023     1    12 2023-01-12     34.2              25
#> 13:    150.05   -27.85  2023     1    13 2023-01-13     33.6              25
#> 14:    150.05   -27.85  2023     1    14 2023-01-14     32.2              25
#> 15:    150.05   -27.85  2023     1    15 2023-01-15     34.2              25
#> 16:    150.05   -27.85  2023     1    16 2023-01-16     33.7              25
#> 17:    150.05   -27.85  2023     1    17 2023-01-17     34.8              25
#> 18:    150.05   -27.85  2023     1    18 2023-01-18     34.4              25
#> 19:    150.05   -27.85  2023     1    19 2023-01-19     35.0              25
#> 20:    150.05   -27.85  2023     1    20 2023-01-20     33.4              25
#> 21:    150.05   -27.85  2023     1    21 2023-01-21     33.6              25
#> 22:    150.05   -27.85  2023     1    22 2023-01-22     33.3              25
#> 23:    150.05   -27.85  2023     1    23 2023-01-23     34.6              25
#> 24:    150.05   -27.85  2023     1    24 2023-01-24     35.1              25
#> 25:    150.05   -27.85  2023     1    25 2023-01-25     38.1              25
#> 26:    150.05   -27.85  2023     1    26 2023-01-26     38.7              25
#> 27:    150.05   -27.85  2023     1    27 2023-01-27     34.3              25
#> 28:    150.05   -27.85  2023     1    28 2023-01-28     36.7              25
#> 29:    150.05   -27.85  2023     1    29 2023-01-29     37.7              25
#> 30:    150.05   -27.85  2023     1    30 2023-01-30     37.1              25
#> 31:    150.05   -27.85  2023     1    31 2023-01-31     31.6              25
#>     longitude latitude  year month   day       date air_tmax air_tmax_source
#>     air_tmin air_tmin_source  elev_m  extracted
#>        <num>           <int>  <char>     <Date>
#>  1:     19.5              25 254.5 m 2024-05-20
#>  2:     19.6              25 254.5 m 2024-05-20
#>  3:     20.6              25 254.5 m 2024-05-20
#>  4:     20.9              25 254.5 m 2024-05-20
#>  5:     21.4              25 254.5 m 2024-05-20
#>  6:     16.4              25 254.5 m 2024-05-20
#>  7:     19.8              25 254.5 m 2024-05-20
#>  8:     18.4              25 254.5 m 2024-05-20
#>  9:     20.7              25 254.5 m 2024-05-20
#> 10:     21.9              25 254.5 m 2024-05-20
#> 11:     21.4              25 254.5 m 2024-05-20
#> 12:     20.8              25 254.5 m 2024-05-20
#> 13:     18.3              25 254.5 m 2024-05-20
#> 14:     18.6              25 254.5 m 2024-05-20
#> 15:     19.0              25 254.5 m 2024-05-20
#> 16:     19.7              25 254.5 m 2024-05-20
#> 17:     18.5              25 254.5 m 2024-05-20
#> 18:     18.1              25 254.5 m 2024-05-20
#> 19:     18.7              25 254.5 m 2024-05-20
#> 20:     20.6              25 254.5 m 2024-05-20
#> 21:     17.7              25 254.5 m 2024-05-20
#> 22:     20.0              25 254.5 m 2024-05-20
#> 23:     20.3              25 254.5 m 2024-05-20
#> 24:     20.4              25 254.5 m 2024-05-20
#> 25:     20.2              25 254.5 m 2024-05-20
#> 26:     21.3              25 254.5 m 2024-05-20
#> 27:     23.1              25 254.5 m 2024-05-20
#> 28:     18.5              25 254.5 m 2024-05-20
#> 29:     21.6              25 254.5 m 2024-05-20
#> 30:     24.7              25 254.5 m 2024-05-20
#> 31:     21.9              25 254.5 m 2024-05-20
#>     air_tmin air_tmin_source  elev_m  extracted
```

### Example 3: Get Data Drill APSIM Formated Data

For APSIM users, SILO provides an endpoint that serves APSIM formatted data ready for use in this modelling framework.
The `get_data_drill_apsim()` function works just as `get_data_drill()`, it just returns an object that is an {[apsimx]} `met` class rather than a `data.table` and there is no need to specify values as those are predetermined by the API endpoint.
The [write_apsim_met()] function is reexported from [{apsimx}](https://cran.r-project.org/package=apsimx) for convenience in saving .met files.


``` r
library(weatherOz)

(
  southwood_apsim <- get_data_drill_apsim(
    latitude = -27.85,
    longitude = 150.05,
    start_date = "20230101",
    end_date = "20230131",
    api_key = Sys.getenv("SILO_API_KEY")
  )
)
#> Warning in amp_apsim_met(x): Year: 2023 was not used for calculating 'amp'
#> because less than 300 days were present
#> Warning in amp_apsim_met(met): Year: 2023 was not used for calculating 'amp'
#> because less than 300 days were present
#> weather.met.weather 
#> site =  
#> latitude = -27.85  (DECIMAL DEGREES) 
#> longitude = 150.05  (DECIMAL DEGREES) 
#> tav = 27.5516666666667 (oC) ! calculated annual average ambient temperature 2024-05-20 18:46:24.944582 
#> amp = 0 !calculated with the apsimx R package: 2024-05-20 18:46:24.949116 
#> year day radn maxt mint rain evap vp code 
#> () () (MJ/m^2) (oC) (oC) (mm) (mm) (hPa) () 
#>   year day radn maxt mint rain evap   vp   code
#> 1 2023   2 30.4 35.3 19.6  0.0  8.2 17.0 422222
#> 2 2023   3 22.7 36.6 20.6  0.0  6.1 18.2 422222
#> 3 2023   4 22.0 39.1 20.9  0.0  8.5 21.0 422222
#> 4 2023   5 12.1 31.4 21.4  3.6  6.5 18.1 422222
#> 5 2023   6 30.1 34.4 16.4  0.0  6.7 17.1 422222
#> 6 2023   7 27.6 33.4 19.8  0.0  5.7 15.7 422222
```

### Getting Patched Point Data

Patched Point data are derived from actual BOM station observations (PatchedPoint) data and may or may not be interpolated.
Be sure to note the `data_source` column to be sure.
The functions, `get_patched_point()` and `get_patched_point_apsim()` work exactly as their Data Drill counterparts except that they require a station code, `station_code`, rather than longitude and latitude values for the geographic location.

### Example 4: Get Data Drill Data Using Defaults

Using the station code for Wongan Hills, WA, get all values for June of 2021.


``` r
library(weatherOz)

(
  wongan_hills <- get_patched_point(
    station_code = "008137",
    start_date = "20210601",
    end_date = "20210630",
    api_key = Sys.getenv("SILO_API_KEY")
  )
)
#> You have requested station observation data but some rows in this
#> dataset have data codes for interpolated data.
#> Check the 'data_source' columns and `get_patched_point()` or
#> `get_data_drill()` documentation for further details on codes and
#> references.
#>     station_code station_name  year month   day       date air_tmax
#>           <fctr>       <char> <num> <num> <int>     <Date>    <num>
#>  1:       008137 Wongan Hills  2021     6     1 2021-06-01     15.0
#>  2:       008137 Wongan Hills  2021     6     2 2021-06-02     17.4
#>  3:       008137 Wongan Hills  2021     6     3 2021-06-03     18.6
#>  4:       008137 Wongan Hills  2021     6     4 2021-06-04     20.3
#>  5:       008137 Wongan Hills  2021     6     5 2021-06-05     20.5
#>  6:       008137 Wongan Hills  2021     6     6 2021-06-06     20.5
#>  7:       008137 Wongan Hills  2021     6     7 2021-06-07     15.8
#>  8:       008137 Wongan Hills  2021     6     8 2021-06-08     16.3
#>  9:       008137 Wongan Hills  2021     6     9 2021-06-09     18.2
#> 10:       008137 Wongan Hills  2021     6    10 2021-06-10     17.9
#> 11:       008137 Wongan Hills  2021     6    11 2021-06-11     18.5
#> 12:       008137 Wongan Hills  2021     6    12 2021-06-12     18.5
#> 13:       008137 Wongan Hills  2021     6    13 2021-06-13     19.2
#> 14:       008137 Wongan Hills  2021     6    14 2021-06-14     17.7
#> 15:       008137 Wongan Hills  2021     6    15 2021-06-15     15.1
#> 16:       008137 Wongan Hills  2021     6    16 2021-06-16     17.4
#> 17:       008137 Wongan Hills  2021     6    17 2021-06-17     16.0
#> 18:       008137 Wongan Hills  2021     6    18 2021-06-18     17.3
#> 19:       008137 Wongan Hills  2021     6    19 2021-06-19     17.7
#> 20:       008137 Wongan Hills  2021     6    20 2021-06-20     12.1
#> 21:       008137 Wongan Hills  2021     6    21 2021-06-21     11.5
#> 22:       008137 Wongan Hills  2021     6    22 2021-06-22     13.5
#> 23:       008137 Wongan Hills  2021     6    23 2021-06-23     14.1
#> 24:       008137 Wongan Hills  2021     6    24 2021-06-24     14.7
#> 25:       008137 Wongan Hills  2021     6    25 2021-06-25     16.4
#> 26:       008137 Wongan Hills  2021     6    26 2021-06-26     17.7
#> 27:       008137 Wongan Hills  2021     6    27 2021-06-27     15.7
#> 28:       008137 Wongan Hills  2021     6    28 2021-06-28     18.5
#> 29:       008137 Wongan Hills  2021     6    29 2021-06-29     15.6
#> 30:       008137 Wongan Hills  2021     6    30 2021-06-30     14.2
#>     station_code station_name  year month   day       date air_tmax
#>     air_tmax_source air_tmin air_tmin_source  elev_m et_morton_actual
#>               <int>    <num>           <int>  <char>            <num>
#>  1:               0      5.5               0 283.0 m              1.0
#>  2:               0      5.1               0 283.0 m              1.7
#>  3:               0      5.9               0 283.0 m              1.2
#>  4:               0      4.8               0 283.0 m              1.1
#>  5:               0      4.6               0 283.0 m              1.2
#>  6:              25      4.6               0 283.0 m              1.4
#>  7:              25      5.4              25 283.0 m              1.5
#>  8:               0      4.8              25 283.0 m              0.6
#>  9:               0      7.2               0 283.0 m              0.2
#> 10:               0      9.9               0 283.0 m              1.0
#> 11:               0      9.8               0 283.0 m              1.9
#> 12:               0     11.3               0 283.0 m              1.5
#> 13:               0      6.7               0 283.0 m              1.1
#> 14:               0      9.5              25 283.0 m              1.4
#> 15:               0      5.2               0 283.0 m              1.1
#> 16:               0      5.2               0 283.0 m              0.9
#> 17:               0      4.9               0 283.0 m              1.1
#> 18:               0      3.5               0 283.0 m              1.2
#> 19:               0      3.4               0 283.0 m              0.6
#> 20:               0      6.0               0 283.0 m              0.9
#> 21:               0      6.9               0 283.0 m              0.9
#> 22:               0      1.9               0 283.0 m              1.0
#> 23:               0      3.4               0 283.0 m              1.1
#> 24:               0      2.8               0 283.0 m              0.8
#> 25:               0      2.1               0 283.0 m              1.3
#> 26:              25      1.7               0 283.0 m              0.8
#> 27:              25      4.2              25 283.0 m              0.4
#> 28:               0      9.1              25 283.0 m              1.4
#> 29:               0     10.6               0 283.0 m              1.5
#> 30:               0      4.0               0 283.0 m              1.1
#>     air_tmax_source air_tmin air_tmin_source  elev_m et_morton_actual
#>     et_morton_actual_source et_morton_potential et_morton_potential_source
#>                       <int>               <num>                      <int>
#>  1:                      26                 1.0                         26
#>  2:                      26                 1.9                         26
#>  3:                      26                 2.5                         26
#>  4:                      26                 2.8                         26
#>  5:                      26                 2.6                         26
#>  6:                      26                 2.4                         26
#>  7:                      26                 1.9                         26
#>  8:                      26                 2.4                         26
#>  9:                      26                 1.7                         26
#> 10:                      26                 1.0                         26
#> 11:                      26                 1.9                         26
#> 12:                      26                 2.0                         26
#> 13:                      26                 2.4                         26
#> 14:                      26                 1.4                         26
#> 15:                      26                 1.2                         26
#> 16:                      26                 1.9                         26
#> 17:                      26                 1.5                         26
#> 18:                      26                 2.3                         26
#> 19:                      26                 2.8                         26
#> 20:                      26                 0.9                         26
#> 21:                      26                 1.2                         26
#> 22:                      26                 2.1                         26
#> 23:                      26                 1.9                         26
#> 24:                      26                 2.5                         26
#> 25:                      26                 2.0                         26
#> 26:                      26                 2.6                         26
#> 27:                      26                 1.4                         26
#> 28:                      26                 1.7                         26
#> 29:                      26                 1.5                         26
#> 30:                      26                 1.1                         26
#>     et_morton_actual_source et_morton_potential et_morton_potential_source
#>     et_morton_wet et_morton_wet_source et_short_crop et_short_crop_source
#>             <num>                <int>         <num>                <int>
#>  1:           1.0                   26           1.0                   26
#>  2:           1.8                   26           1.4                   26
#>  3:           1.9                   26           1.7                   26
#>  4:           1.9                   26           1.9                   26
#>  5:           1.9                   26           1.9                   26
#>  6:           1.9                   26           1.8                   26
#>  7:           1.7                   26           1.3                   26
#>  8:           1.5                   26           1.7                   26
#>  9:           0.9                   26           2.0                   26
#> 10:           1.0                   26           0.7                   26
#> 11:           1.9                   26           1.3                   26
#> 12:           1.8                   26           1.4                   26
#> 13:           1.8                   26           1.6                   26
#> 14:           1.4                   26           1.1                   26
#> 15:           1.2                   26           1.1                   26
#> 16:           1.4                   26           1.4                   26
#> 17:           1.3                   26           1.2                   26
#> 18:           1.7                   26           1.5                   26
#> 19:           1.7                   26           1.8                   26
#> 20:           0.9                   26           0.8                   26
#> 21:           1.0                   26           1.0                   26
#> 22:           1.6                   26           1.3                   26
#> 23:           1.5                   26           1.3                   26
#> 24:           1.6                   26           1.5                   26
#> 25:           1.7                   26           1.4                   26
#> 26:           1.7                   26           1.7                   26
#> 27:           0.9                   26           1.7                   26
#> 28:           1.6                   26           1.3                   26
#> 29:           1.5                   26           0.9                   26
#> 30:           1.1                   26           1.0                   26
#>     et_morton_wet et_morton_wet_source et_short_crop et_short_crop_source
#>     et_tall_crop et_tall_crop_source evap_comb evap_comb_source
#>            <num>               <int>     <num>            <int>
#>  1:          1.2                  26       1.7               25
#>  2:          1.8                  26       1.3               25
#>  3:          2.3                  26       1.6               25
#>  4:          2.7                  26       1.9               25
#>  5:          2.6                  26       2.4               25
#>  6:          2.4                  26       1.4               25
#>  7:          1.7                  26       2.6               25
#>  8:          2.4                  26       3.4               25
#>  9:          3.1                  26       2.2               25
#> 10:          0.7                  26       1.0               25
#> 11:          1.6                  26       1.2               25
#> 12:          1.8                  26       1.6               25
#> 13:          2.3                  26       2.3               25
#> 14:          1.3                  26       2.5               25
#> 15:          1.4                  26       1.3               25
#> 16:          2.0                  26       1.8               25
#> 17:          1.6                  26       2.5               25
#> 18:          2.1                  26       1.9               25
#> 19:          2.6                  26       1.6               25
#> 20:          1.0                  26       1.6               25
#> 21:          1.2                  26       2.1               25
#> 22:          1.9                  26       1.2               25
#> 23:          1.7                  26       1.0               25
#> 24:          2.2                  26       1.6               25
#> 25:          2.0                  26       1.7               25
#> 26:          2.5                  26       2.7               25
#> 27:          2.5                  26       1.5               25
#> 28:          1.7                  26       2.6               25
#> 29:          1.1                  26       2.1               25
#> 30:          1.2                  26       2.5               25
#>     et_tall_crop et_tall_crop_source evap_comb evap_comb_source
#>     evap_morton_lake evap_morton_lake_source evap_pan evap_pan_source evap_syn
#>                <num>                   <int>    <num>           <int>    <num>
#>  1:              1.0                      26      1.7              25      1.7
#>  2:              1.8                      26      1.3              25      2.0
#>  3:              1.9                      26      1.6              25      2.2
#>  4:              1.9                      26      1.9              25      2.5
#>  5:              1.9                      26      2.4              25      2.4
#>  6:              1.9                      26      1.4              25      2.4
#>  7:              1.7                      26      2.6              25      2.0
#>  8:              1.5                      26      3.4              25      2.2
#>  9:              1.0                      26      2.2              25      2.5
#> 10:              0.9                      26      1.0              25      1.5
#> 11:              1.9                      26      1.2              25      1.9
#> 12:              1.8                      26      1.6              25      1.9
#> 13:              1.8                      26      2.3              25      2.2
#> 14:              1.4                      26      2.5              25      1.8
#> 15:              1.2                      26      1.3              25      1.8
#> 16:              1.4                      26      1.8              25      2.1
#> 17:              1.3                      26      2.5              25      1.9
#> 18:              1.7                      26      1.9              25      2.2
#> 19:              1.7                      26      1.6              25      2.3
#> 20:              0.9                      26      1.6              25      1.6
#> 21:              1.0                      26      2.1              25      1.7
#> 22:              1.6                      26      1.2              25      2.0
#> 23:              1.5                      26      1.0              25      2.0
#> 24:              1.6                      26      1.6              25      2.1
#> 25:              1.7                      26      1.7              25      2.1
#> 26:              1.7                      26      2.7              25      2.4
#> 27:              0.9                      26      1.5              25      2.2
#> 28:              1.6                      26      2.6              25      2.0
#> 29:              1.5                      26      2.1              25      1.6
#> 30:              1.1                      26      2.5              25      1.8
#>     evap_morton_lake evap_morton_lake_source evap_pan evap_pan_source evap_syn
#>     evap_syn_source  extracted latitude longitude   mslp mslp_source radiation
#>               <int>     <Date>    <num>     <num>  <num>       <int>     <num>
#>  1:              26 2024-05-20 -30.8917  116.7186 1022.6           0       8.9
#>  2:              26 2024-05-20 -30.8917  116.7186 1026.5           0      12.4
#>  3:              26 2024-05-20 -30.8917  116.7186 1028.6           0      12.5
#>  4:              26 2024-05-20 -30.8917  116.7186 1027.2           0      12.7
#>  5:              26 2024-05-20 -30.8917  116.7186 1023.8           0      12.6
#>  6:              26 2024-05-20 -30.8917  116.7186 1020.1           0      12.6
#>  7:              26 2024-05-20 -30.8917  116.7186 1027.6          25      12.3
#>  8:              26 2024-05-20 -30.8917  116.7186 1026.9           0      11.0
#>  9:              26 2024-05-20 -30.8917  116.7186 1015.0           0       7.1
#> 10:              26 2024-05-20 -30.8917  116.7186 1010.2           0       6.8
#> 11:              26 2024-05-20 -30.8917  116.7186 1013.8           0      12.0
#> 12:              26 2024-05-20 -30.8917  116.7186 1014.6           0      11.3
#> 13:              26 2024-05-20 -30.8917  116.7186 1019.5           0      12.0
#> 14:              26 2024-05-20 -30.8917  116.7186 1018.0           0       9.4
#> 15:              26 2024-05-20 -30.8917  116.7186 1021.5           0       9.2
#> 16:              26 2024-05-20 -30.8917  116.7186 1026.8           0      10.3
#> 17:              26 2024-05-20 -30.8917  116.7186 1031.7           0       9.9
#> 18:              26 2024-05-20 -30.8917  116.7186 1030.1           0      12.3
#> 19:              26 2024-05-20 -30.8917  116.7186 1024.9           0      12.2
#> 20:              26 2024-05-20 -30.8917  116.7186 1016.4           0       4.6
#> 21:              26 2024-05-20 -30.8917  116.7186 1012.3           0       8.3
#> 22:              26 2024-05-20 -30.8917  116.7186 1022.6           0      12.1
#> 23:              26 2024-05-20 -30.8917  116.7186 1026.7           0      11.3
#> 24:              26 2024-05-20 -30.8917  116.7186 1029.7           0      12.2
#> 25:              26 2024-05-20 -30.8917  116.7186 1027.6           0      12.4
#> 26:              26 2024-05-20 -30.8917  116.7186 1024.8           0      12.4
#> 27:              26 2024-05-20 -30.8917  116.7186 1014.1          25       7.2
#> 28:              26 2024-05-20 -30.8917  116.7186 1013.9           0      10.6
#> 29:              26 2024-05-20 -30.8917  116.7186 1016.7           0       6.8
#> 30:              26 2024-05-20 -30.8917  116.7186 1026.5           0       9.2
#>     evap_syn_source  extracted latitude longitude   mslp mslp_source radiation
#>     radiation_source rainfall rainfall_source rh_tmax rh_tmax_source rh_tmin
#>                <int>    <num>           <int>   <num>          <int>   <num>
#>  1:               42      0.0               0    68.1             26   100.0
#>  2:               42      0.0               0    57.9             26   100.0
#>  3:               42      0.0               0    50.9             26   100.0
#>  4:               42      0.0               0    44.9             26   100.0
#>  5:               42      0.0               0    45.6             26   100.0
#>  6:               42      0.0               0    48.1             26   100.0
#>  7:               42      0.0               0    59.6             26   100.0
#>  8:               42      0.0               0    47.0             26   100.0
#>  9:               42      0.0               0    39.3             26    80.8
#> 10:               42      1.2               0    81.5             26   100.0
#> 11:               42      3.4               0    68.1             26   100.0
#> 12:               42      2.4               0    67.7             26   100.0
#> 13:               42      0.2               0    52.2             26   100.0
#> 14:               42      0.4               0    70.6             26   100.0
#> 15:               42      0.0               0    63.5             26   100.0
#> 16:               42      0.2               0    53.9             26   100.0
#> 17:               42      0.0               0    58.9             26   100.0
#> 18:               42      0.0               0    49.7             26   100.0
#> 19:               42      0.0               0    43.5             26   100.0
#> 20:               42      0.0               0    73.0             26   100.0
#> 21:               42     16.4               0    73.7             26   100.0
#> 22:               42      0.4               0    51.7             26   100.0
#> 23:               42      0.0               0    56.0             26   100.0
#> 24:               42      0.0               0    47.9             26   100.0
#> 25:               42      0.0               0    50.4             26   100.0
#> 26:               42      0.0               0    42.0             26   100.0
#> 27:               42      0.0               0    43.8             26    94.6
#> 28:               42      1.8               0    63.9             26   100.0
#> 29:               42      3.8               0    79.0             26   100.0
#> 30:               42      2.6               0    65.5             26   100.0
#>     radiation_source rainfall rainfall_source rh_tmax rh_tmax_source rh_tmin
#>     rh_tmin_source    vp vp_deficit vp_deficit_source vp_source
#>              <int> <num>      <num>             <int>     <int>
#>  1:             26  11.6        3.0                26         0
#>  2:             26  11.5        4.8                26         0
#>  3:             26  10.9        6.6                26         0
#>  4:             26  10.7        8.0                26         0
#>  5:             26  11.0        7.8                26         0
#>  6:             26  11.6        7.2                26         0
#>  7:             26  10.7        4.5                26        25
#>  8:             26   8.7        6.7                26         0
#>  9:             26   8.2        9.3                26         0
#> 10:             26  16.7        1.4                26         0
#> 11:             26  14.5        4.1                26         0
#> 12:             26  14.4        4.6                26         0
#> 13:             26  11.6        6.7                26         0
#> 14:             26  14.3        3.5                26         0
#> 15:             26  10.9        3.7                26         0
#> 16:             26  10.7        5.6                26         0
#> 17:             26  10.7        4.5                26         0
#> 18:             26   9.8        6.0                26         0
#> 19:             26   8.8        7.3                26         0
#> 20:             26  10.3        2.5                26         0
#> 21:             26  10.0        2.6                26         0
#> 22:             26   8.0        4.8                26         0
#> 23:             26   9.0        4.5                26         0
#> 24:             26   8.0        5.8                26         0
#> 25:             26   9.4        5.4                26         0
#> 26:             26   8.5        7.2                26         0
#> 27:             26   7.8        7.0                26        25
#> 28:             26  13.6        4.7                26         0
#> 29:             26  14.0        2.3                26         0
#> 30:             26  10.6        3.1                26         0
#>     rh_tmin_source    vp vp_deficit vp_deficit_source vp_source
```

## Working With SILO Metadata

Two functions are provided to assist in fetching metadata about the stations.
 * `find_nearby_stations()`, which returns a `data.table` with the nearest weather stations to a given geographic point or known station either in the DPIRD or BOM (from SILO) networks.
 * `get_stations_metadata()`, which returns a `data.table` with the latest and most up-to-date information available from the Weather 2.0 API on the stations' geographic locations, hardware details, *e.g.,* wind mast height, and recording capabilities.

### Finding Nearby Stations

Functions for searching metadata in the SILO network do not require an API key except where you may also interact with the DPIRD API.

### Example 5: Finding Stations Nearby a Known Station

Query stations and return BOM's stations nearest to the DPIRD Northam, WA station, "NO", returning stations with 50 km of this station.
This requires a DPIRD API key as we're using that station as the starting point.


``` r
library(weatherOz)

(
  wa_stn <- find_nearby_stations(
    station_code = "010111",
    distance_km = 50,
    which_api = "silo"
  )
)
#> No SILO stations found within a radius of <50 km
#>  from `station_code` 010111.
#> NULL
```

### Example 6: Finding Stations Nearby a Given Longitude and Latitude

Using the longitude and latitude for Northam, WA, find only BOM stations within a 50km radius of this geographic point.


``` r
library(weatherOz)

(
  wa_stn_lonlat <- find_nearby_stations(
    longitude = 116.6620,
    latitude = -31.6540,
    distance_km = 50,
    which_api = "silo"
  )
)
#> No SILO stations found within a radius of <50 km
#>  from coordinates 116.662 and -31.654 (lon/lat).
#> NULL
```

### Example 7: Finding Stations in Both the DPIRD and SILO Data Sets

Query stations nearest BOM's Northam, WA station, "010111" and return both DPIRD and SILO/BOM stations within 50 km of this station.
Note the use of an API key for the DPIRD network and that `which_api` is set to "all".


``` r
library(weatherOz)

(
  wa_stn_all <- find_nearby_stations(
    station_code = "010111",
    distance_km = 50,
    api_key = Sys.getenv("DPIRD_API_KEY"),
    which_api = "all"
  )
)
#> No SILO stations found within a radius of <50 km
#>  from `station_code` 010111.
#> Error: HTTP (400400) - Bad RequestBad Request
#> `latitude` is required.`longitude` is required.
```

### Example 8: Finding Stations in a Named Place

Using `find_stations_in()` is different than `find_nearby_stations()` as it finds any stations that fall within a boundary or a named place that you provide rather than using a single point to search from.
For a detailed working example of how to use this with a geospatial polygon and finding both BOM and DPIRD stations, please see the "weatherOz for DPIRD" vignette.


``` r
place <- find_stations_in(x = "Toowoomba Qld",
                         which_api = "SILO",
                         include_closed = TRUE)
#> Waiting 2s for retry backoff ■■■■■■■■■■■■■■■ [K[KWaiting 4s for retry backoff
#> ■■■■■■■■■ [KWaiting 4s for retry backoff ■■■■■■■■■■■ [KWaiting 4s for retry
#> backoff ■■■■■■■■■■■■ [KWaiting 4s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 4s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 4s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 4s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting
#> 4s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 4s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 4s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 4s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 4s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 4s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 4s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [K[KWaiting 2s for retry backoff
#> ■■■■■■■■■■■■■■■ [K[KWaiting 8s for retry backoff ■■■■■ [KWaiting 8s for retry
#> backoff ■■■■■■ [KWaiting 8s for retry backoff ■■■■■■ [KWaiting 8s for retry
#> backoff ■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■ [KWaiting 8s for retry
#> backoff ■■■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■■■ [KWaiting 8s for
#> retry backoff ■■■■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■■■■ [KWaiting
#> 8s for retry backoff ■■■■■■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 8s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 8s for
#> retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■■■■■■■■■■
#> [KWaiting 8s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting
#> 8s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 8s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 8s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [K[KWaiting 6s for retry backoff ■■■■■■
#> [KWaiting 6s for retry backoff ■■■■■■■ [KWaiting 6s for retry backoff ■■■■■■■■
#> [KWaiting 6s for retry backoff ■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■ [KWaiting 6s for retry backoff ■■■■■■■■■■■ [KWaiting 6s for retry
#> backoff ■■■■■■■■■■■■ [KWaiting 6s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 6s
#> for retry backoff ■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff ■■■■■■■■■■■■■■■
#> [KWaiting 6s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting
#> 6s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 6s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 6s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [K[KWaiting 34s for retry backoff ■■ [KWaiting
#> 34s for retry backoff ■■ [KWaiting 34s for retry backoff ■■ [KWaiting 34s for
#> retry backoff ■■ [KWaiting 34s for retry backoff ■■■ [KWaiting 34s for retry
#> backoff ■■■ [KWaiting 34s for retry backoff ■■■ [KWaiting 34s for retry backoff
#> ■■■ [KWaiting 34s for retry backoff ■■■ [KWaiting 34s for retry backoff ■■■■
#> [KWaiting 34s for retry backoff ■■■■ [KWaiting 34s for retry backoff ■■■■
#> [KWaiting 34s for retry backoff ■■■■ [KWaiting 34s for retry backoff ■■■■
#> [KWaiting 34s for retry backoff ■■■■ [KWaiting 34s for retry backoff ■■■■■
#> [KWaiting 34s for retry backoff ■■■■■ [KWaiting 34s for retry backoff ■■■■■
#> [KWaiting 34s for retry backoff ■■■■■ [KWaiting 34s for retry backoff ■■■■■
#> [KWaiting 34s for retry backoff ■■■■■ [KWaiting 34s for retry backoff ■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■ [KWaiting 34s for retry backoff ■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■ [KWaiting 34s for retry backoff ■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■ [KWaiting 34s for
#> retry backoff ■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■ [KWaiting 34s
#> for retry backoff ■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■ [KWaiting
#> 34s for retry backoff ■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■ [KWaiting 34s for
#> retry backoff ■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■ [KWaiting
#> 34s for retry backoff ■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■ [KWaiting 34s
#> for retry backoff ■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■ [KWaiting 34s for
#> retry backoff ■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■ [KWaiting 34s for
#> retry backoff ■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 34s for
#> retry backoff ■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 34s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 34s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 34s
#> for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 34s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 34s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 34s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 34s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 34s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for
#> retry backoff ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 34s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [K[KWaiting 54s for retry backoff ■■ [KWaiting
#> 54s for retry backoff ■■ [KWaiting 54s for retry backoff ■■ [KWaiting 54s for
#> retry backoff ■■ [KWaiting 54s for retry backoff ■■ [KWaiting 54s for retry
#> backoff ■■ [KWaiting 54s for retry backoff ■■ [KWaiting 54s for retry backoff
#> ■■ [KWaiting 54s for retry backoff ■■ [KWaiting 54s for retry backoff ■■
#> [KWaiting 54s for retry backoff ■■■ [KWaiting 54s for retry backoff ■■■
#> [KWaiting 54s for retry backoff ■■■ [KWaiting 54s for retry backoff ■■■
#> [KWaiting 54s for retry backoff ■■■ [KWaiting 54s for retry backoff ■■■
#> [KWaiting 54s for retry backoff ■■■ [KWaiting 54s for retry backoff ■■■
#> [KWaiting 54s for retry backoff ■■■■ [KWaiting 54s for retry backoff ■■■■
#> [KWaiting 54s for retry backoff ■■■■ [KWaiting 54s for retry backoff ■■■■
#> [KWaiting 54s for retry backoff ■■■■ [KWaiting 54s for retry backoff ■■■■
#> [KWaiting 54s for retry backoff ■■■■ [KWaiting 54s for retry backoff ■■■■
#> [KWaiting 54s for retry backoff ■■■■ [KWaiting 54s for retry backoff ■■■■■
#> [KWaiting 54s for retry backoff ■■■■■ [KWaiting 54s for retry backoff ■■■■■
#> [KWaiting 54s for retry backoff ■■■■■ [KWaiting 54s for retry backoff ■■■■■
#> [KWaiting 54s for retry backoff ■■■■■ [KWaiting 54s for retry backoff ■■■■■
#> [KWaiting 54s for retry backoff ■■■■■ [KWaiting 54s for retry backoff ■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■ [KWaiting 54s for retry backoff ■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■ [KWaiting 54s for retry backoff ■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■ [KWaiting 54s for retry backoff ■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■ [KWaiting 54s for retry backoff ■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 54s for
#> retry backoff ■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 54s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 54s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 54s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 54s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [K[KWaiting 57s for retry backoff ■ [KWaiting
#> 57s for retry backoff ■■ [KWaiting 57s for retry backoff ■■ [KWaiting 57s for
#> retry backoff ■■ [KWaiting 57s for retry backoff ■■ [KWaiting 57s for retry
#> backoff ■■ [KWaiting 57s for retry backoff ■■ [KWaiting 57s for retry backoff
#> ■■ [KWaiting 57s for retry backoff ■■ [KWaiting 57s for retry backoff ■■
#> [KWaiting 57s for retry backoff ■■■ [KWaiting 57s for retry backoff ■■■
#> [KWaiting 57s for retry backoff ■■■ [KWaiting 57s for retry backoff ■■■
#> [KWaiting 57s for retry backoff ■■■ [KWaiting 57s for retry backoff ■■■
#> [KWaiting 57s for retry backoff ■■■ [KWaiting 57s for retry backoff ■■■
#> [KWaiting 57s for retry backoff ■■■ [KWaiting 57s for retry backoff ■■■■
#> [KWaiting 57s for retry backoff ■■■■ [KWaiting 57s for retry backoff ■■■■
#> [KWaiting 57s for retry backoff ■■■■ [KWaiting 57s for retry backoff ■■■■
#> [KWaiting 57s for retry backoff ■■■■ [KWaiting 57s for retry backoff ■■■■
#> [KWaiting 57s for retry backoff ■■■■ [KWaiting 57s for retry backoff ■■■■
#> [KWaiting 57s for retry backoff ■■■■ [KWaiting 57s for retry backoff ■■■■■
#> [KWaiting 57s for retry backoff ■■■■■ [KWaiting 57s for retry backoff ■■■■■
#> [KWaiting 57s for retry backoff ■■■■■ [KWaiting 57s for retry backoff ■■■■■
#> [KWaiting 57s for retry backoff ■■■■■ [KWaiting 57s for retry backoff ■■■■■
#> [KWaiting 57s for retry backoff ■■■■■ [KWaiting 57s for retry backoff ■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■ [KWaiting 57s for retry backoff ■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■ [KWaiting 57s for retry backoff ■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■ [KWaiting 57s for retry backoff ■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■ [KWaiting 57s for retry backoff ■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 57s for
#> retry backoff ■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 57s
#> for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 57s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 57s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 57s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [K[KWaiting 60s for retry backoff ■ [KWaiting
#> 60s for retry backoff ■■ [KWaiting 60s for retry backoff ■■ [KWaiting 60s for
#> retry backoff ■■ [KWaiting 60s for retry backoff ■■ [KWaiting 60s for retry
#> backoff ■■ [KWaiting 60s for retry backoff ■■ [KWaiting 60s for retry backoff
#> ■■ [KWaiting 60s for retry backoff ■■ [KWaiting 60s for retry backoff ■■
#> [KWaiting 60s for retry backoff ■■■ [KWaiting 60s for retry backoff ■■■
#> [KWaiting 60s for retry backoff ■■■ [KWaiting 60s for retry backoff ■■■
#> [KWaiting 60s for retry backoff ■■■ [KWaiting 60s for retry backoff ■■■
#> [KWaiting 60s for retry backoff ■■■ [KWaiting 60s for retry backoff ■■■
#> [KWaiting 60s for retry backoff ■■■ [KWaiting 60s for retry backoff ■■■
#> [KWaiting 60s for retry backoff ■■■ [KWaiting 60s for retry backoff ■■■■
#> [KWaiting 60s for retry backoff ■■■■ [KWaiting 60s for retry backoff ■■■■
#> [KWaiting 60s for retry backoff ■■■■ [KWaiting 60s for retry backoff ■■■■
#> [KWaiting 60s for retry backoff ■■■■ [KWaiting 60s for retry backoff ■■■■
#> [KWaiting 60s for retry backoff ■■■■ [KWaiting 60s for retry backoff ■■■■
#> [KWaiting 60s for retry backoff ■■■■■ [KWaiting 60s for retry backoff ■■■■■
#> [KWaiting 60s for retry backoff ■■■■■ [KWaiting 60s for retry backoff ■■■■■
#> [KWaiting 60s for retry backoff ■■■■■ [KWaiting 60s for retry backoff ■■■■■
#> [KWaiting 60s for retry backoff ■■■■■ [KWaiting 60s for retry backoff ■■■■■
#> [KWaiting 60s for retry backoff ■■■■■ [KWaiting 60s for retry backoff ■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■ [KWaiting 60s for retry backoff ■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■ [KWaiting 60s for retry backoff ■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■ [KWaiting 60s for retry backoff ■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■ [KWaiting 60s for retry backoff ■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■ [KWaiting 60s for retry backoff ■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 60s for
#> retry backoff ■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■ [KWaiting 60s
#> for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting
#> 60s for retry backoff ■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> [KWaiting 60s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [KWaiting 60s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ [K[K
#> Error in `httr2::req_perform()`:
#> ! Failed to perform HTTP request.
#> Caused by error in `curl::curl_fetch_memory()`:
#> ! Timeout was reached: [nominatim.openstreetmap.org] Resolving timed out after 10000 milliseconds
```

``` r
place
#> Error in eval(expr, envir, enclos): object 'place' not found
```

### Example 9: Finding Stations in a Bounding Box for Melbourne

Using a (generous) bounding box for Melbourne, Vic using only the SILO API for BOM stations, no API key is needed.


``` r
bbox <- find_stations_in(
  x = c(144.470215, -38.160476, 145.612793, -37.622934),
  which_api = "SILO",
  include_closed = TRUE
)
#> Error: Please check your longitude, `-38.160476`, to be sure it is valid for Australian data.
```

``` r
bbox
#> Error in eval(expr, envir, enclos): object 'bbox' not found
```

### Example 10: Finding the Station Nearest the Centroid of a Bounding Box

Using the same bounding box but only find a single open station nearest the centroid of the bounding box.
This will return a single value in this case as there is only one polygon.
For queries where the polygon has 'n' parts, 'n' results will be returned.


``` r
centroid <- find_stations_in(
  x = c(144.470215, -38.160476, 145.612793, -37.622934),
  which_api = "SILO",
  include_closed = FALSE,
  centroid = TRUE
)
#> Error: Please check your longitude, `-38.160476`, to be sure it is valid for Australian data.
```

``` r
centroid
#> Error in eval(expr, envir, enclos): object 'centroid' not found
```

### Getting Station Metadata for the SILO Network Stations

The `get_stations_metadata()` function is shared with the DPIRD functions as well, so this function will retrieve data from both weather APIs.
Shown here is how to use it for SILO data only.

### Example 11: Get SILO Station Metadata

The `get_stations_metadata()` function allows you to get details about the stations themselves for stations in the DPIRD and SILO (BOM) networks in one function.
Here we demonstrate how to get the metadata for the SILO stations only.


``` r
library(weatherOz)

(metadata <- get_stations_metadata(which_api = "silo"))
#> Key: <station_code>
#> Empty data.table (0 rows and 11 cols): station_code,station_name,start,end,latitude,longitude...
```
## Using Metadata to Get Weather Data for a Whole State

Using the metadata, we can get all weather data from stations in a single state like so.


``` r
library(weatherOz)
library(data.table)
#> data.table 1.15.4 using 2 threads (see ?getDTthreads).  Latest news: r-datatable.com
#> 
#> Attaching package: 'data.table'
#> 
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last
```

``` r

metadata <- get_stations_metadata(which_api = "silo")

# Subset to the required state
metadata_wa <- subset(metadata, state == "WA")

# Select first 10 to demo
first_ten <- as.list(as.character(metadata_wa$station_code))[1:10]

# Loop through each station_code and give proper names
# We've wrapped it in `suppressMessages()` to keep the output a bit quieter
# as most of the data have interpolated values in them that will repeat for
# every set.

suppressMessages(
  x <-
    lapply(
      X = first_ten,
      FUN = get_patched_point,
      start_date = "20001201",
      end_date = "20001205",
      values = "all",
      api_key = Sys.getenv("SILO_API_KEY")
    )
)
#> Error: Please supply a valid `station_code`.
```

``` r

names(x) <- unlist(first_ten)

# Create dataset with station_code column id
rbindlist(x, idcol = "station_code")
#> Error: Input is data.table but should be a plain list of items to be stacked
```

# References
