# CRAN NOTE avoidance
utils::globalVariables(
  c(
    "actual_state",
    "end",
    "lat",
    "lon",
    "obs_time_local",
    "obs_time_utc",
    "product_id",
    "r",
    "site",
    "state",
    "station_code",
    "station_name",
    "status",
    "state_code",
    "state_from_latlon",
    "start",
    "stations_site_list",
    "wmo"
  )
)
